### ISSUE TITLE
Using a vals ref+awsssm:// source as a value "file"

### ISSUE THREAD

**Issue by jhohertz** [roboll/helmfile#990]
I am trying to something like this, where some values come from a file, and others come from a small blob of YAML stored in SSM. I can't quite seem to get the syntax right:

```
    values:
      - "./vars/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml"
      - "ref+awsssm://helm/secrets/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}?region=us-east-1"
```
That results in a SIGSEGV as it, I think, tries to treat the YAML retrieved as a file name.

```
    values:
      - "./vars/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml"
      - <<: "ref+awsssm://helm/secrets/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}?region=us-east-1"
```
This results in `yaml: map merge requires map or sequence of maps as the value`.

If I push the retrieved items down a node it may work, but I need the whole of the fetched item to be used as the YAML.

This seems like it would be a really common use-case... I must be missing something obvious.

**Comment by mumoshu** [comment]
> If I push the retrieved items down a node it may work, but I need the whole of the fetched item to be used as the YAML.

@jhohertz Very interesting use-case! Unfortunately, it isn't supported yet.

`ref`s, as of today, is for replacing values in YAML hashes only, not the hashes as the whole.
Probably we need to enhance the syntax a bit if we'd need to support it.

What if it looked like this?

With the inline hash sytnax:

```
values:
- "./vars/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml"
- {"ref+awsssm://helm/secrets/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}?region=us-east-1":{}}
```

Or with the indented syntax:

```
values:
- "./vars/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml"
- "ref+awsssm://helm/secrets/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}?region=us-east-1": {}
```

In `{}`, we may add more options about how it renders and gets merged into values in the future.

**Comment by mumoshu** [comment]
I've implemented what I've proposed in #991
I'd appreciate it if you could try it out and report back if it works or not!

**Comment by jhohertz** [comment]
I'll give it a try! Thanks for having a look into this!

**Comment by jhohertz** [comment]
Sorry no luck yet... I am just getting the URL as-is in the values file, I've tried both flavours you suggested above.

Haven't had a chance yet to look through the PR to see if I can understand what's wrong.

**Comment by jhohertz** [comment]
I did rebuild the `vals` executable and I can see the new syntax working there, so it must be some assumption in the `helmfile` code that needs adjustment

**Comment by jhohertz** [comment]
@mumoshu : Still not sure why I can't get this to work in helmfile. I've re-built helmfile with debug lines before and after the vals rendering, and see the same before and after. I see the module bumped to the right version from #991, so I don't think it's that.

I am at a loss to say why.. I thought at first it might be the way the items were packed into an array before being passed to vals.Eval, tried a variant to separate the calls for each item... (such that the call for this item should be the same as the one I can see working on the CLI) and it still fails to substitute.

**Comment by mumoshu** [comment]
@jhohertz Hey! Thank you so much for your help.

You are absolutely correct that `vals` alone is able to render it correctly:

```
$ cat helmfile.990.yaml
releases:
- name: issue990
  chart: stable/envoy
  values:
  - foo: FOO
  - "ref+file://vals.yaml": {}

$ cat vals.yaml
bar: BAZ

$ vals eval -f helmfile.990.yaml
releases:
  - chart: stable/envoy
    name: issue990
    values:
      - foo: FOO
      - bar: BAZ
```

There should be something going wrong in Helmfile.

**Comment by mumoshu** [comment]
I believe this is the problematic code:

```
	merge := func(strmap map[string]interface{}, k string, opts interface{}) (bool, error) {
		_, ok := opts.(map[string]interface{})
		if !ok {
			return false, nil
		}
```

https://github.com/variantdev/vals/blob/de375c5be6879de7619ed2c091347b638f0617d9/pkg/expansion/maputil.go#L10-L14

Where I see the right part(value) of the YAML document `"ref+file://vals.yaml": {}` is accidentally `map[interface{}]interface{}`:
![image](https://user-images.githubusercontent.com/22009/69470981-21d92080-0dde-11ea-9ee9-a97a582e22d0.png)

We need to loosen the condition to accept not only `map[string]interface{}` but also `map[interface{}]interface{}`.

**Comment by mumoshu** [comment]
Okay after some work I confirmed it to work as expected:

```
$ cat helmfile.990.yaml
releases:
- name: issue990
  chart: stable/envoy
  values:
  - foo: FOO
  - "ref+file://vals.yaml": {}

$ cat vals.yaml
bar: BAZ
image:
  tag: foobarbaz

$ helmfile -f helmfile.990.yaml template | grep foobarbaz
Fetching stable/envoy
Templating release=issue990, chart=/var/folders/lx/53d8_kgd26vf5_drrg89wkvc0000gp/T/245740236/issue990/latest/stable/envoy/envoy
          image: "envoyproxy/envoy:foobarbaz"
```

**Comment by jhohertz** [comment]
This is great! Confirmed it's working well on this end! Thank you so much for implementing this!
